# Generated by Django 5.0.6 on 2024-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('MKT', 'Marketing'), ('FIN', 'Finance'), ('OPS', 'Operations'), ('IM', 'Infrastructure Management')], max_length=3),
        ),
    ]
